# Generated by Django 3.1 on 2020-08-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplist',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
