# Generated by Django 3.1 on 2020-08-20 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0003_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoplist',
            name='important',
        ),
        migrations.RemoveField(
            model_name='shoplist',
            name='memo',
        ),
    ]
