# Generated by Django 3.1 on 2020-08-20 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0004_auto_20200821_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='shoplist',
            name='datecompleted',
        ),
    ]
