# Generated by Django 3.1 on 2020-08-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0005_auto_20200821_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
